"""Per-residue Coulomb/LJ decomposition via ``gmx mdrun -rerun`` (T5b).

Answers "how much of the mutation's effect is direct electrostatics, and with
which neighbours?" by re-evaluating the force field on already-generated frames
with ``energygrps`` set, so GROMACS reports the short-range Coulomb and
Lennard-Jones energy *between* the mutation site and its environment.

This is the only analysis in the plan that needs the original topology: energy
group decomposition is a force-field quantity, not something recoverable from
coordinates. It therefore requires ``topol.top`` (or a ``.tpr``) matching the
trajectory atom-for-atom.

Uncertainty uses block averaging with the block length taken from ``g`` in
``window.json``. Consecutive frames of an MD trajectory are heavily correlated,
so a naive standard error over frames would understate the true uncertainty by
roughly ``sqrt(g)`` — a factor of 4-5 on these trajectories.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

import numpy as np


def write_index(
    groups: dict[str, np.ndarray], path: str | Path, per_line: int = 15
) -> Path:
    """Write a GROMACS ``.ndx`` from zero-based atom indices.

    GROMACS index files are 1-based; the conversion happens here so callers can
    pass MDAnalysis ``AtomGroup.indices`` straight through.
    """
    lines = []
    for name, indices in groups.items():
        one_based = np.asarray(indices, dtype=np.int64) + 1
        if one_based.size == 0:
            raise ValueError(f"index group {name!r} is empty")
        lines.append(f"[ {name} ]")
        for start in range(0, one_based.size, per_line):
            chunk = one_based[start:start + per_line]
            lines.append(" ".join(f"{i:6d}" for i in chunk))
    path = Path(path)
    path.write_text("\n".join(lines) + "\n")
    return path


def build_groups(
    universe, site: int, radius: float = 10.0, selection: str = "protein"
) -> dict[str, np.ndarray]:
    """``{site, shell}`` atom index groups around the mutation site.

    The shell is expanded to *whole residues* — an energy group that cuts a
    residue in half splits its charge group and makes the reported Coulomb term
    depend on where the cut fell rather than on the physics.

    GROMACS puts every atom not listed into an automatic ``rest`` group, so
    those two groups are all that need defining.
    """
    site_atoms = universe.select_atoms(f"({selection}) and resid {site}")
    if len(site_atoms) == 0:
        raise ValueError(f"resid {site} matched no atoms in selection {selection!r}")

    shell = universe.select_atoms(
        f"({selection}) and (around {radius} (resid {site})) and not resid {site}"
    ).residues.atoms

    if len(shell) == 0:
        raise ValueError(f"no residues within {radius} Å of resid {site}")

    return {f"site{site}": site_atoms.indices, "shell": shell.indices}


RERUN_MDP = """\
; Auto-generated by rotmd for an energy-group rerun (no dynamics).
integrator      = md
nsteps          = 0
cutoff-scheme   = Verlet
nstlist         = 1
coulombtype     = {coulombtype}
rcoulomb        = {rcoulomb}
vdwtype         = cutoff
rvdw            = {rvdw}
pbc             = {pbc}
constraints     = none
energygrps      = {energygrps}
"""


def write_rerun_mdp(
    path: str | Path,
    energygrps: list[str],
    coulombtype: str = "PME",
    rcoulomb: float = 1.2,
    rvdw: float = 1.2,
    pbc: str = "xyz",
) -> Path:
    """Write the ``.mdp`` driving the rerun.

    ``nsteps = 0`` because a rerun evaluates energies on supplied frames and
    never integrates. Cutoffs should match the production run: changing
    ``rcoulomb`` changes what "short-range Coulomb" means and makes the numbers
    incomparable with the original simulation.
    """
    path = Path(path)
    path.write_text(RERUN_MDP.format(
        energygrps=" ".join(energygrps), coulombtype=coulombtype,
        rcoulomb=rcoulomb, rvdw=rvdw, pbc=pbc,
    ))
    return path


def _run(cmd: list[str], cwd: Path, what: str) -> subprocess.CompletedProcess:
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"{what} failed (exit {result.returncode}):\n"
            f"{(result.stderr or result.stdout)[-3000:]}"
        )
    return result


def run_rerun(
    gmx: str,
    mdp: Path,
    structure: Path,
    topology: Path,
    trajectory: Path,
    index: Path,
    workdir: Path,
    maxwarn: int = 2,
) -> Path:
    """``grompp`` then ``mdrun -rerun``; returns the resulting ``.edr``."""
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    tpr = workdir / "rerun.tpr"
    edr = workdir / "rerun.edr"

    _run(
        [gmx, "grompp", "-f", str(mdp), "-c", str(structure), "-p", str(topology),
         "-n", str(index), "-o", str(tpr), "-maxwarn", str(maxwarn)],
        workdir, "gmx grompp",
    )
    _run(
        [gmx, "mdrun", "-s", str(tpr), "-rerun", str(trajectory),
         "-e", str(edr), "-g", str(workdir / "rerun.log"), "-nt", "1"],
        workdir, "gmx mdrun -rerun",
    )
    return edr


def read_edr(edr: str | Path) -> dict[str, np.ndarray]:
    """Read a ``.edr`` into ``{term: array}`` using panedr."""
    import panedr

    frame = panedr.edr_to_df(str(edr))
    return {str(col): frame[col].to_numpy() for col in frame.columns}


def block_error(values: np.ndarray, g: float) -> dict[str, float]:
    """Mean and block-averaged standard error for a correlated series.

    Blocks are ``ceil(g)`` frames long — the point at which successive blocks
    are approximately independent — and the error is the standard error over
    block means. With fewer than two whole blocks no honest error can be
    quoted, so it comes back as NaN rather than as a falsely small number.
    """
    values = np.asarray(values, dtype=np.float64)
    n = values.size
    block = max(1, int(np.ceil(g)))
    n_blocks = n // block

    if n_blocks < 2:
        return {
            "mean": float(values.mean()) if n else float("nan"),
            "stderr": float("nan"),
            "n_blocks": n_blocks,
            "block_size": block,
        }

    means = values[: n_blocks * block].reshape(n_blocks, block).mean(axis=1)
    return {
        "mean": float(values.mean()),
        "stderr": float(means.std(ddof=1) / np.sqrt(n_blocks)),
        "n_blocks": int(n_blocks),
        "block_size": block,
    }


def select_pair_terms(terms: dict[str, np.ndarray], group_a: str, group_b: str) -> dict[str, str]:
    """Find the ``Coul-SR``/``LJ-SR`` columns for a group pair.

    GROMACS writes these as ``Coul-SR:A-B`` but does not promise the ordering
    of A and B, so both are tried.
    """
    found = {}
    for kind in ("Coul-SR", "LJ-SR", "Coul-14", "LJ-14"):
        for a, b in ((group_a, group_b), (group_b, group_a)):
            key = f"{kind}:{a}-{b}"
            if key in terms:
                found[kind] = key
                break
    return found


def coulomb_decomposition(
    topology_top: str | Path,
    structure: str | Path,
    trajectory: str | Path,
    site: int,
    workdir: str | Path,
    g: float = 1.0,
    radius: float = 10.0,
    selection: str = "protein",
    gmx: str | None = None,
    mdp_options: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Full T5b: rerun the window and report site-shell Coulomb and LJ energies."""
    import MDAnalysis as mda

    from rotmd.analysis.apbs import find_tool

    gmx = gmx or find_tool("gmx")
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    universe = mda.Universe(str(structure))
    groups = build_groups(universe, site, radius=radius, selection=selection)
    index = write_index(groups, workdir / "index.ndx")
    names = list(groups)

    mdp = write_rerun_mdp(workdir / "rerun.mdp", names, **(mdp_options or {}))
    edr = run_rerun(
        gmx, mdp, Path(structure), Path(topology_top), Path(trajectory), index, workdir
    )

    terms = read_edr(edr)
    pair = select_pair_terms(terms, names[0], names[1])
    if not pair:
        available = [k for k in terms if ":" in k]
        raise RuntimeError(
            f"no energy-group pair terms for {names[0]}-{names[1]} in the .edr. "
            f"Available pair terms: {available[:10]}"
        )

    result: dict[str, Any] = {
        "site": np.int64(site),
        "radius": np.float64(radius),
        "n_frames": np.int64(len(next(iter(terms.values())))),
        "group_site_atoms": np.int64(len(groups[names[0]])),
        "group_shell_atoms": np.int64(len(groups[names[1]])),
        "g": np.float64(g),
    }
    for kind, column in pair.items():
        values = terms[column]
        stats = block_error(values, g)
        tag = kind.replace("-", "_")
        result[f"{tag}_series"] = values
        result[f"{tag}_mean"] = np.float64(stats["mean"])
        result[f"{tag}_stderr"] = np.float64(stats["stderr"])
        result[f"{tag}_n_blocks"] = np.int64(stats["n_blocks"])
        result[f"{tag}_block_size"] = np.int64(stats["block_size"])
    return result
