"""T5c: Poisson-Boltzmann electrostatics.

The pure functions (grid sizing, input generation, output parsing) run
everywhere. The end-to-end calculation is marked ``integration`` and skips
unless both external binaries are present.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import numpy as np
import pytest

from rotmd.analysis.apbs import (
    KJ_PER_KCAL,
    find_tool,
    grid_dimensions,
    parse_apbs_energy,
    read_pqr,
    sample_frame_indices,
    write_apbs_input,
)

_VALID_DIME = (33, 49, 65, 81, 97, 113, 129, 161, 193, 225, 257)

PQR_SAMPLE = """\
REMARK   1 generated by pdb2pqr
ATOM      1  N   MET A   1      10.000  10.000  10.000 -0.3000 1.8240
ATOM      2  CA  MET A   1      12.000  10.000  10.000  0.2100 1.9080
ATOM      3  C   MET A   1      10.000  14.000  10.000  0.5100 1.9080
ATOM      4  O   MET A   1      10.000  10.000  16.000 -0.5100 1.6612
TER
END
"""


def _apbs_tools_available() -> bool:
    have_apbs = shutil.which("apbs") is not None
    bindir = Path(sys.executable).parent
    have_pqr = shutil.which("pdb2pqr30") is not None or (bindir / "pdb2pqr30").is_file()
    return bool(have_apbs and have_pqr)


needs_tools = pytest.mark.skipif(
    not _apbs_tools_available(), reason="apbs and/or pdb2pqr30 not installed"
)


# ---------------------------------------------------------------------------
# PQR parsing
# ---------------------------------------------------------------------------

def test_read_pqr_extracts_coordinates_and_radii(tmp_path):
    path = tmp_path / "x.pqr"
    path.write_text(PQR_SAMPLE)
    coords, radii = read_pqr(path)

    assert coords.shape == (4, 3)
    np.testing.assert_allclose(coords[0], [10.0, 10.0, 10.0])
    np.testing.assert_allclose(radii, [1.8240, 1.9080, 1.9080, 1.6612])


def test_read_pqr_rejects_a_file_with_no_atoms(tmp_path):
    path = tmp_path / "empty.pqr"
    path.write_text("REMARK nothing here\nEND\n")
    with pytest.raises(ValueError, match="no ATOM/HETATM"):
        read_pqr(path)


# ---------------------------------------------------------------------------
# Grid sizing
# ---------------------------------------------------------------------------

def test_grid_dime_values_are_legal_for_apbs_multigrid():
    """APBS requires dime = c*2^(l+1)+1; an arbitrary value aborts the run."""
    coords, radii = np.array([[0.0, 0, 0], [30.0, 40.0, 50.0]]), np.array([1.5, 1.5])
    grid = grid_dimensions(coords, radii)
    for value in grid["dime"]:
        assert value in _VALID_DIME


def test_grid_boxes_follow_the_psize_heuristic():
    coords = np.array([[0.0, 0.0, 0.0], [10.0, 20.0, 30.0]])
    radii = np.array([1.0, 1.0])
    grid = grid_dimensions(coords, radii)

    extent = np.array([12.0, 22.0, 32.0])          # span + radii on both sides
    np.testing.assert_allclose(grid["extent"], extent)
    np.testing.assert_allclose(grid["cglen"], 1.7 * extent)
    np.testing.assert_allclose(grid["fglen"], np.minimum(20.0 + extent, 1.7 * extent))
    np.testing.assert_allclose(grid["centre"], [5.0, 10.0, 15.0])


def test_grid_is_capped_to_bound_memory():
    # A huge molecule must not request a 500^3 grid.
    coords = np.array([[0.0, 0, 0], [400.0, 400.0, 400.0]])
    grid = grid_dimensions(coords, np.array([1.0, 1.0]), max_dime=161)
    assert max(grid["dime"]) <= 161


def test_finer_spacing_requests_a_larger_grid():
    coords, radii = np.array([[0.0, 0, 0], [40.0, 40.0, 40.0]]), np.array([1.0, 1.0])
    coarse = grid_dimensions(coords, radii, fine_spacing=1.0)
    fine = grid_dimensions(coords, radii, fine_spacing=0.3)
    assert max(fine["dime"]) >= max(coarse["dime"])


# ---------------------------------------------------------------------------
# Input generation
# ---------------------------------------------------------------------------

def test_input_contains_two_states_differing_only_in_solvent_dielectric(tmp_path):
    """ΔG_elec is meaningful only if everything but sdie cancels."""
    grid = grid_dimensions(*read_pqr_from(tmp_path))
    path = write_apbs_input(tmp_path / "apbs.in", "frame.pqr", grid, pdie=2.0, sdie=78.54)
    text = path.read_text()

    assert "elec name solv" in text
    assert "elec name ref" in text
    assert "sdie 78.54" in text          # solvated
    assert text.count("sdie 2.0") == 1   # reference collapses onto pdie
    assert text.count("pdie 2.0") == 2   # identical solute dielectric in both
    assert "print elecEnergy solv - ref end" in text
    # Both blocks must share one grid, or the difference is a grid artefact.
    assert text.count(f"dime {grid['dime'][0]}") == 2


def read_pqr_from(tmp_path):
    path = tmp_path / "frame.pqr"
    path.write_text(PQR_SAMPLE)
    return read_pqr(path)


def test_potential_map_is_requested_only_when_asked(tmp_path):
    grid = grid_dimensions(*read_pqr_from(tmp_path))
    plain = write_apbs_input(tmp_path / "a.in", "f.pqr", grid).read_text()
    withdx = write_apbs_input(tmp_path / "b.in", "f.pqr", grid, potential_dx="pot").read_text()

    assert "write pot dx" not in plain
    assert withdx.count("write pot dx pot") == 1   # solvated state only


def test_ionic_strength_is_written_into_both_states(tmp_path):
    grid = grid_dimensions(*read_pqr_from(tmp_path))
    text = write_apbs_input(tmp_path / "a.in", "f.pqr", grid, ionic_strength=0.15).read_text()
    assert text.count("ion charge 1 conc 0.15") == 2


# ---------------------------------------------------------------------------
# Output parsing
# ---------------------------------------------------------------------------

def test_parse_takes_the_final_global_net_energy():
    """Earlier per-state totals are not solvation energies and must be ignored."""
    output = """
      Total electrostatic energy = 1.466301820312E+05 kJ/mol
      Total electrostatic energy = 2.123812697782E+05 kJ/mol
      Local net energy (PE 0) = -7.543418135448E+03 kJ/mol
      Global net ELEC energy = -7.543418135448E+03 kJ/mol
    """
    assert parse_apbs_energy(output) == pytest.approx(-7543.418135448)


def test_parse_reports_failure_with_context():
    with pytest.raises(ValueError, match="no 'Global net ELEC energy'"):
        parse_apbs_energy("APBS aborted: could not allocate grid")


def test_kj_to_kcal_conversion_constant():
    assert KJ_PER_KCAL == pytest.approx(4.184)
    assert -7543.42 / KJ_PER_KCAL == pytest.approx(-1802.92, abs=0.01)


# ---------------------------------------------------------------------------
# Frame sampling
# ---------------------------------------------------------------------------

def test_sampling_spans_the_window_and_starts_at_t0():
    idx = sample_frame_indices(n_frames=1000, start=300, n_samples=10)
    assert idx.min() == 300
    assert idx.max() == 999
    assert len(idx) == 10
    assert np.all(np.diff(idx) > 0)


def test_sampling_is_deterministic():
    a = sample_frame_indices(1000, 0, 25)
    b = sample_frame_indices(1000, 0, 25)
    np.testing.assert_array_equal(a, b)


def test_sampling_cannot_exceed_available_frames():
    idx = sample_frame_indices(n_frames=10, start=5, n_samples=100)
    assert len(idx) <= 5
    assert idx.max() <= 9


def test_sampling_rejects_a_window_past_the_end():
    with pytest.raises(ValueError, match="beyond the"):
        sample_frame_indices(n_frames=10, start=10, n_samples=5)


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

def test_find_tool_locates_a_script_beside_the_interpreter(tmp_path, monkeypatch):
    """pip console scripts sit next to python and are often not on PATH."""
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    (fake_bin / "made_up_tool").write_text("#!/bin/sh\n")
    monkeypatch.setattr(sys, "executable", str(fake_bin / "python"))
    assert find_tool("made_up_tool") == str(fake_bin / "made_up_tool")


def test_find_tool_error_names_how_to_install():
    with pytest.raises(FileNotFoundError, match="micromamba install"):
        find_tool("definitely_not_a_real_binary_xyz")


# ---------------------------------------------------------------------------
# End to end (needs apbs + pdb2pqr30)
# ---------------------------------------------------------------------------

@needs_tools
@pytest.mark.integration
def test_pb_energy_on_a_real_frame(tmp_path):
    """A real PDB2PQR + APBS run must give a negative solvation free energy."""
    pytest.importorskip("MDAnalysis")
    data = Path.home() / ".cache/rotmd-testdata/n75k_prot.gro"
    if not data.exists():
        pytest.skip("real-data fixture not built")

    import MDAnalysis as mda

    from rotmd.analysis.apbs import run_single_frame

    u = mda.Universe(str(data))
    pdb = tmp_path / "frame.pdb"
    u.select_atoms("protein").write(str(pdb))

    result = run_single_frame(pdb, tmp_path / "work")
    # Polar solvation of a charged protein is strongly favourable; the sign is
    # the meaningful assertion, the magnitude is system-specific.
    assert result["dG_elec_kJ"] < 0
    assert result["dG_elec_kcal"] == pytest.approx(result["dG_elec_kJ"] / KJ_PER_KCAL)
    assert result["n_atoms"] > 1000
