#!/usr/bin/env bash
# =============================================================================
# scripts/hpc/install-jupyter-kernel.sh
#
# Register the rotmd container (rotmd.sif, built from the `kernel` Dockerfile
# stage) as a *user-level* Jupyter kernel. Run this on the HPC login node (or
# anywhere your home directory is the same one JupyterHub spawns from).
#
# Why a kernel and not `pip install`:
#   On a JupyterHub / `module load` Jupyter you cannot install into the Hub's
#   base environment, and pytim/freesasa are sdist-only (need a compiler). This
#   drops a kernelspec under ~/.local/share/jupyter/kernels that the Hub's
#   JupyterLab discovers automatically. Selecting it runs the kernel *inside*
#   the container, so the notebook gets the exact pinned scientific stack while
#   the JupyterLab frontend stays whatever the Hub provides.
#
# The container must contain ipykernel — build it with:
#   ./scripts/dev.sh save-kernel            # exports rotmd-kernel.tar
#   apptainer build rotmd.sif docker-archive://rotmd-kernel.tar
#
# Usage:
#   bash scripts/hpc/install-jupyter-kernel.sh --sif /scratch/$USER/rotmd.sif
#
#   Options:
#     --sif PATH        Path to rotmd.sif (required).
#     --name NAME       Kernel dir name (default: rotmd).
#     --display NAME    Display name in the JupyterLab launcher (default: rotmd).
#     --bind PATH       Extra bind mount (repeatable). /scratch/$USER is always
#                       bound; add data/home paths your notebooks read here.
#     --threads N       Fallback thread count when $SLURM_CPUS_PER_TASK is unset
#                       (default: 4).
# =============================================================================

set -euo pipefail

SIF=""
NAME="rotmd"
DISPLAY_NAME="rotmd"
THREADS_DEFAULT="4"
EXTRA_BINDS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sif)     SIF="$2"; shift 2 ;;
        --name)    NAME="$2"; shift 2 ;;
        --display) DISPLAY_NAME="$2"; shift 2 ;;
        --bind)    EXTRA_BINDS+=("$2"); shift 2 ;;
        --threads) THREADS_DEFAULT="$2"; shift 2 ;;
        -h|--help)
            sed -n '/^# Usage:/,/^# ===/p' "${BASH_SOURCE[0]}" | grep '^#' | sed 's/^# \?//'
            exit 0 ;;
        *)
            echo "ERROR: unknown argument: $1" >&2
            echo "Run with --help for usage." >&2
            exit 1 ;;
    esac
done

if [[ -z "$SIF" ]]; then
    echo "ERROR: --sif is required (path to rotmd.sif)." >&2
    echo "Run with --help for usage." >&2
    exit 1
fi

# Resolve to an absolute path so the kernelspec works regardless of cwd.
SIF="$(readlink -f "$SIF")"
if [[ ! -f "$SIF" ]]; then
    echo "ERROR: SIF not found: $SIF" >&2
    exit 1
fi

if ! command -v apptainer &>/dev/null && ! command -v singularity &>/dev/null; then
    echo "WARNING: neither apptainer nor singularity found on PATH." >&2
    echo "  The kernel launcher calls 'apptainer'; make sure it is available" >&2
    echo "  in the environment JupyterHub spawns (e.g. via 'module load')." >&2
fi

KERNEL_DIR="${HOME}/.local/share/jupyter/kernels/${NAME}"
mkdir -p "$KERNEL_DIR"

LAUNCH="${KERNEL_DIR}/launch.sh"
KERNEL_JSON="${KERNEL_DIR}/kernel.json"

# ---------------------------------------------------------------------------
# Build the --bind list. /scratch/$USER is bound so notebooks can reach data;
# add more with --bind. Users on a Hub whose runtime dir is XDG_RUNTIME_DIR
# (/run/user/$UID) may need to bind that too — see the note printed at the end.
# ---------------------------------------------------------------------------
BIND_LINES=""
add_bind() { BIND_LINES+="  --bind $1 \\"$'\n'; }
add_bind "/scratch/\$USER"
for b in "${EXTRA_BINDS[@]}"; do
    add_bind "$b"
done

# ---------------------------------------------------------------------------
# launch.sh — wrapper so we can pull the thread count from the SLURM
# allocation the Hub spawned into. kernelspec argv cannot expand env vars, so
# the wrapper does it. "$@" carries the "-f {connection_file}" that JupyterHub
# appends when it starts the kernel.
# ---------------------------------------------------------------------------
cat > "$LAUNCH" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/hpc/install-jupyter-kernel.sh — edit binds/threads
# here and restart your JupyterLab to pick up changes.
NT=\${SLURM_CPUS_PER_TASK:-${THREADS_DEFAULT}}
exec apptainer exec \\
${BIND_LINES}  --env NUMBA_NUM_THREADS=\$NT \\
  --env OMP_NUM_THREADS=\$NT \\
  --env OPENBLAS_NUM_THREADS=\$NT \\
  "${SIF}" \\
  python -m ipykernel_launcher "\$@"
EOF
chmod +x "$LAUNCH"

# ---------------------------------------------------------------------------
# kernel.json — interrupt_mode=message because signal-based Ctrl-C does not
# reliably cross the `apptainer exec` boundary.
# ---------------------------------------------------------------------------
cat > "$KERNEL_JSON" <<EOF
{
  "display_name": "${DISPLAY_NAME}",
  "language": "python",
  "argv": [
    "${LAUNCH}",
    "-f",
    "{connection_file}"
  ],
  "interrupt_mode": "message"
}
EOF

echo "Installed kernel '${NAME}':"
echo "  ${KERNEL_JSON}"
echo "  ${LAUNCH}"
echo "  -> container: ${SIF}"
echo
echo "Restart your JupyterLab and pick '${DISPLAY_NAME}' from the launcher."
echo
echo "If the kernel fails to connect ('No such file or directory' on the"
echo "connection file), your Hub writes it outside the auto-bound \$HOME and /tmp."
echo "Add the runtime dir to the launcher, e.g.:"
echo "  --bind /run/user/\$(id -u)"
